apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: product-api
data:
  gcp_project_id: "sublime-flux-414616"
  splunk_hec_endpoint: "http://otel-collector:4318"
  splunk_tunnel_endpoint: "http://35.193.5.99:8088"
